services:
  ingest:
    build: ./services/ingest
    ports: ["8001:8001"]
    environment:
      - EMBED_SERVICE_URL=http://embed_indexing:8002/embed/
  embed_indexing:
    build: ./services/embed_indexing
    ports: ["8002:8002"]
  query:
    build: ./services/query
    ports: ["8003:8003"]
    environment:
      - EMBED_QUERY_URL=http://embed_indexing:8002/query/
      - LLM_SERVICE_URL=http://llm:8004/generate
  llm:
    build: ./services/llm
    ports: ["8004:8004"]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
